#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define PADDLE_MARGIN 20

#define PADDLE_WIDTH 20
#define PADDLE_HEIGHT 100

#define BALL_WIDTH 20
#define BALL_HEIGHT 20

#define PADDLE_VELOCITY 6
#define BALL_VELOCITY 4
#define BALL_VELOCITY_INCREMENT 2
#define MAX_BALL_VELOCITY 16

#define TARGET_SCORE 10

#define SEPARATOR_LINE_WIDTH 5
#define SEPARATOR_LINE_DASH_HEIGHT 10
#define SEPARATOR_LINE_DASH_MARGIN 20

#endif